### ISSUE TITLE
记住密码部分希望能加密一下

### ISSUE THREAD

**Issue by Loyisa** [starmcc/qs-beanfun#4]
该启动器有在登录时记住账号和密码的功能 但是似乎并没有保存到配置文件中的密码进行加密

相关代码部分:
https://github.com/starmcc/qs-beanfun/blob/aa1e4004e1ea9195410f850173dd1e7dd8301078/src/main/java/com/starmcc/beanfun/handler/AccountHandler.java#L41

希望可以在将来的版本中能加密一下储存的密码 谢谢！

**Comment by starmcc** [comment]
在开源的前提下加密其实并没有什么意义，不过这边会对其加密一下的，感谢支持~

**Comment by starmcc** [comment]
已对其进行加密处理 [version by 3.0.1](https://github.com/starmcc/qs-beanfun/releases/tag/3.0.1)
