### ISSUE TITLE
win11登录器无法启动游戏

### ISSUE THREAD

**Issue by faitian995** [starmcc/qs-beanfun#7]
使用4.0.1版本，启动游戏提示要安装VC环境，下载安装后，再次启动还是提示，无法启动游戏，原来使用3.0版本的时候没这个问题呀？是什么原因呢？

**Comment by starmcc** [comment]
[检查注册表](https://github.com/starmcc/qs-beanfun/blob/9d2edfcacd39b3b2ee0bbd14b765626cd109f0a1/src/main/java/com/starmcc/beanfun/manager/impl/WindowManagerImpl.java#L52)

```
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\
```
的每一项中，属性为DisplayName是否存在 `Microsoft Visual C++ 20`  且包含 `Runtime`字符。

后续考虑优化该检查，使之更人性化，可暂时使用`3.0.1`版本。

也可以使用下方的reg文件暂时解决，解压双击运行即可。
[vc.zip](https://github.com/starmcc/qs-beanfun/files/9690767/vc.zip)
